language: scala
scala:
- 2.11.8
script:
- sbt -Dpb.config=perfect-build.json.travis ++$TRAVIS_SCALA_VERSION clean test publish sonatypeRelease
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_9065a2ed1687_key -iv $encrypted_9065a2ed1687_iv
  -in credentials.sonatype-nexus.properties.enc -out credentials.sonatype-nexus.properties
  -d
